version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: football_fantasy
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - fantasy
  web:
    build:
      context: .
    ports:
      - "2000:8000"
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - fantasy
    environment:
      DATABASE_NAME: football_fantasy
      DATABASE_USER: root
      DATABASE_PASSWORD: root

networks:
  fantasy:
    driver: bridge
